# Generated by Django 6.0.7 on 2026-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='UG Legon Poultry Team', max_length=100)),
                ('summary', models.TextField(help_text='Short preview snippet for card display', max_length=300)),
                ('content', models.TextField()),
                ('cover_image_url', models.URLField(blank=True, help_text='Image link or Unsplash URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
