# Generated by Django 6.0.7 on 2026-07-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Image link or Pexels URL', null=True),
        ),
    ]
