# Generated by Django 6.0.7 on 2026-07-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0002_preorder_amount_paid_preorder_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('STARTER', 'Starter Crumble (Wks 1-2)'), ('GROWER', 'Grower Pellets (Wks 3-4)'), ('FINISHER', 'Finisher Pellets (Wks 5-7)')], max_length=20)),
                ('bags_in_stock', models.IntegerField(default=0)),
                ('bag_weight_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('reorder_threshold', models.IntegerField(default=20, help_text='Minimum bag count before alert')),
                ('cost_per_bag_ghs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('VACCINE', 'Vaccine'), ('ANTIBIOTIC', 'Antibiotic'), ('VITAMIN', 'Supplement')], max_length=50)),
                ('quantity_available', models.IntegerField()),
                ('unit', models.CharField(default='vials', max_length=20)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_consumed_bags', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_consumed_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mortality_count', models.IntegerField(default=0, help_text='Number of dead birds today')),
                ('culled_count', models.IntegerField(default=0, help_text='Sick/weak birds removed')),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='farm.batchmetric')),
            ],
        ),
    ]
