# Generated by Django 6.0.7 on 2026-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(default='Batch #2026-A', max_length=100)),
                ('current_week', models.IntegerField(default=4)),
                ('total_weeks', models.IntegerField(default=7)),
                ('flock_capacity', models.IntegerField(default=10000)),
                ('target_weight', models.CharField(default='2.0 - 2.5 kg', max_length=50)),
                ('mortality_count', models.IntegerField(default=35)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
